[package]
name = "suwayomi-server"
version = "0.1.0"
edition = "2021"

[dependencies]
suwayomi-core = { workspace = true }
suwayomi-db = { workspace = true }
suwayomi-extensions = { workspace = true }
suwayomi-downloader = { workspace = true }
suwayomi-api = { workspace = true }
tokio = { workspace = true }
clap = { workspace = true }
config = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
axum = { workspace = true }
